CREATE_SIGNATURE_ABILITIES_TABLE = (
    """CREATE TABLE IF NOT EXISTS signature_abilities (
        id SERIAL PRIMARY KEY,
        ability_name TEXT NOT NULL,
        ability_type TEXT NOT NULL,
        retainer_id INT NOT NULL REFERENCES retainers(id) ON DELETE CASCADE,
        range_id INT REFERENCES weapon_attack_ranges(id) ON DELETE CASCADE,
        hit_dc INT NOT NULL,
        average_damage INT NOT NULL,
        dice_quantity INT NOT NULL,
        dice_size INT NOT NULL,
        damage_modifier INT NOT NULL,
        damage_type TEXT    
    )"""
)

POPULATE_SIGNATURE_ABILITIES_TABLE = (
        """INSERT INTO signature_abilities (
            ability_name,
            ability_type,
            retainer_id,
            range_id,
            hit_dc,
            average_damage,
            dice_quantity,
            dice_size,
            damage_modifier,
            damage_type
        ) SELECT 
            abilities.name,
            abilities.type,
            retainers.id,
            ranges.id,
            abilities.hit,
            abilities.average,
            abilities.quantity,
            abilities.dice_size,
            abilities.damage_mod,
            abilities.damage_type
        FROM (
            VALUES
                (
                    'melee weapon attack',
                    'weapon attack',
                    'reaver',
                    'melee',
                    6,
                    9,
                    1,
                    12,
                    3,
                    'slashing'
                ),
                (
                    'melee or ranged weapon attack',
                    'weapon attack',
                    'spirit warden',
                    'hybrid',
                    6,
                    9,
                    2,
                    6,
                    2,
                    'slashing'
                ),
                (
                    'melee weapon attack',
                    'weapon attack',
                    'loremaster',
                    'melee',
                    6,
                    6,
                    1,
                    8,
                    2,
                    'slashing'
                ),
                (
                    'melee weapon attack',
                    'weapon attack',
                    'troubadour-warrior',
                    'melee',
                    6,
                    7,
                    1,
                    8,
                    3,
                    'slashing'
                ),
                (
                    'sacred flame',
                    'spell',
                    'curate',
                    'spell 60',
                    13,
                    4,
                    1,
                    8,
                    0,
                    'radiant'
                ),
                (
                    'sacred flame',
                    'spell',
                    'exorcist',
                    'spell 60',
                    13,
                    4,
                    1,
                    8,
                    0,
                    'radiant'
                ),
                (
                    'orison',
                    'special',
                    'healer',
                    null,
                    0,
                    0,
                    0,
                    0,
                    0,
                    null
                ),
                 (
                    'sacred flame',
                    'spell',
                    'shadow priest',
                    'spell 60',
                    13,
                    4,
                    1,
                    8,
                    0,
                    'radiant'
                ),
                (
                    'melee weapon attack',
                    'weapon attack',
                    'stormspeaker',
                    'melee',
                    6,
                    8,
                    2,
                    6,
                    1,
                    'bludgeoning'
                ),
                (
                    'poison spray',
                    'spell',
                    'warden',
                    'spell 10',
                    13,
                    5,
                    1,
                    10,
                    0,
                    'poison'
                ),
                (
                    'melee weapon attack',
                    'weapon attack',
                    'battle priest',
                    'melee',
                    6,
                    8,
                    1,
                    8,
                    4,
                    'bludgeoning'
                ),
                (
                    'poison spray',
                    'spell',
                    'mystic',
                    'spell 10',
                    13,
                    5,
                    1,
                    10,
                    0,
                    'poison'
                ),
                (
                    'melee weapon attack',
                    'weapon attack',
                    'skinwalker',
                    'melee',
                    6,
                    7,
                    2,
                    4,
                    2,
                    'piercing'
                ),
                (
                    'melee weapon attack',
                    'weapon attack',
                    'knight-sorcerer',
                    'melee',
                    6,
                    8,
                    1,
                    8,
                    4,
                    'slashing'
                ),
                (
                    'melee weapon attack',
                    'weapon attack',
                    'swordmaster',
                    'melee',
                    6,
                    11,
                    2,
                    8,
                    2,
                    'slashing'
                ),
                (
                    'melee weapon attack',
                    'weapon attack',
                    'warlord',
                    'melee',
                    6,
                    10,
                    1,
                    12,
                    4,
                    'piercing'
                ),
                (
                    'melee weapon attack',
                    'weapon attack',
                    'acolyte of the way'
                    'melee',
                    6,
                    9,
                    2,
                    4,
                    4,
                    'bludgeoning'
                ),
                (
                    'melee weapon attack',
                    'weapon attack',
                    'acolyte of darkness',
                    'melee',
                    6,
                    9,
                    2,
                    4,
                    4,
                    'bludgeoning'
                ),
                (
                    'melee weapon attack',
                    'weapon attack',
                    'elemental acolyte',
                    'melee',
                    6,
                    7,
                    1,
                    8,
                    3,
                    'bludgeoning'
                ),
                (
                    'melee weapon attack',
                    'weapon attack',
                    'cavalier',
                    'melee',
                    6,
                    9,
                    1,
                    12,
                    3,
                    'piercing'
                ),
                (
                    'melee weapon attack',
                    'weapon attack',
                    'justicar',
                    'melee',
                    6,
                    10,
                    2,
                    6,
                    3,
                    'slashing'
                ),
                (
                    'melee weapon attack',
                    'weapon attack',
                    'knight of the green order',
                    'melee',
                    6,
                    7,
                    1,
                    8,
                    3,
                    'slashing'           
                ),
                (
                    'ranged weapon attack',
                    'weapon attack',
                    'beast lord',
                    'ranged',
                    6,
                    8,
                    1,
                    8,
                    4,
                    'piercing'
                ),
                (
                    'ranged weapon attack',
                    'weapon attack',
                    'tracker',
                    'ranged',
                    6,
                    8,
                    1,
                    8,
                    4,
                    'piercing'
                ),
                (
                    'melee weapon attack',
                    'weapon attack',
                    'executioner',
                    'melee',
                    6,
                    9,
                    2,
                    4,
                    4,
                    'piercing'
                ),
                (
                    'melee weapon attack',
                    'weapon attack',
                    'guild adept',
                    'melee',
                    6,
                    7,
                    1,
                    8,
                    3,
                    'slashing'
                ),
                (
                    'melee weapon attack',
                    'weapon attack',
                    'cutpurse',
                    'melee',
                    6,
                    9,
                    2,
                    6,
                    2,
                    'piercing'
                ),
                (
                    'fire bolt',
                    'spell',
                    'thaumaturgist',
                    'spell 120',
                    6,
                    5,
                    1,
                    10,
                    0,
                    'fire'
                ),
                (
                    'chaos bolt',
                    'special',
                    'chaos mage',
                    null,
                    0,
                    0,
                    0,
                    0,
                    0,
                    null
                ),
                (
                    'eldritch blast',
                    'spell',
                    'alienist',
                    'spell 120',
                    6,
                    5,
                    1,
                    10,
                    0,
                    'force'
                ),
                (
                    'eldritch blast',
                    'spell',
                    'diabolist',
                    'spell 120',
                    6,
                    5,
                    1,
                    10,
                    0,
                    'force'
                ),
                (
                    'eldritch blast',
                    'spell',
                    'exarch',
                    'spell 120',
                    6,
                    5,
                    1,
                    10,
                    0,
                    'force'
                ),
                (
                    'acid splash',
                    'spell',
                    'conjurer',
                    'spell 60',
                    13,
                    3,
                    1,
                    6,
                    0,
                    'acid'
                ),
                (
                    'shocking grasp',
                    'spell',
                    'enchanter',
                    'melee',
                    6,
                    4,
                    1,
                    8,
                    0,
                    'lightning'
                ),
                (
                    'ray of frost',
                    'spell',
                    'evoker'
                    'spell 60',
                    6,
                    4,
                    1,
                    8,
                    0,
                    'cold'
                ),
                (
                    'poison spray',
                    'spell',
                    'illusionist',
                    'spell 10',
                    13,
                    6,
                    1,
                    16,
                    0,
                    'poison'
                ),
                (
                    'chill touch',
                    'spell',
                    'necromancer',
                    'spell 120',
                    6,
                    4,
                    1,
                    8,
                    0,
                    'necrotic'
                ),
                (
                    'fire bolt',
                    'spell',
                    'seer',
                    'spell 120',
                    6,
                    5,
                    1,
                    10,
                    0,
                    'fire'
                ),
                (
                    'fire bolt',
                    'spell',
                    'shaper',
                    'spell 120',
                    6,
                    5,
                    1,
                    10,
                    0,
                    'fire'
                ),
                (
                    'ray of frost',
                    'spell',
                    'theurgist',
                    'spell 60',
                    6,
                    4,
                    1,
                    8,
                    0,
                    'cold'
                )
        )
        """
)